routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::group(['middleware'=>'auth'], function(){
	//Index
	Route::get('/', 'kelasController@index');

	//Kelas
	Route::get('kelas/add','kelasController@create');
	Route::post('kelas/add','kelasController@store');
	Route::get('kelas/{id}/edit','kelasController@edit');
	Route::patch('kelas/{id}/edit','kelasController@update');
	Route::delete('kelas/{id}/delete','kelasController@destroy');

	//Siswa
	Route::get('siswa','SiswaController@index');
	Route::get('siswa/add','SiswaController@create');
	Route::post('siswa/add','SiswaController@store');
	Route::get('siswa/{id}/edit','SiswaController@edit');
	Route::patch('siswa/{id}/edit','SiswaController@update');
	Route::delete('siswa/{id}/delete','SiswaController@destroy');

});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    public $primaryKey = 'id_kelas';

    protected $table = 't_kelas';

    protected $fillable = [
    	'nama_kelas','jurusan'
    ];
}

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    public $primaryKey = "nis";

    protected $table = 't_siswa';

    protected $fillable = [
    	'nis','nama_lengkap','jenis_kelamin','alamat','no_hp','id_kelas','foto'
    ];

    public function getJenisKelaminDisplayAttribute()
    {
    	if(@$this->attributes['jenis_kelamin'] == 'L') return 'Laki-Laki';
    	if(@$this->attributes['jenis_kelamin'] == 'P') return 'Laki-Laki';
    	return '-';

    }

    public function kelas()
    {
    	return $this->hasOne('\App\Kelas','id_kelas','id_kelas');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 't_login';
    public $primaryKey = 'id_login';

    protected $fillable = [
        'nama_user', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiswaController extends Controller
{
	public function index()
	{
		$data['result'] = \App\Siswa::all();
  	 	return view('siswa/index')->with($data);

	}

	public function create()
	{
		return view('siswa/form');
	}

	public function store(Request $re)
	{
		$rules = [
			'nis'			=> 'required|unique:t_siswa',
			'nama_lengkap'	=> 'required|max:100',
			'jenis_kelamin'	=> 'required',
			'alamat'		=> 'required',
			'no_hp'			=> 'required',
			'id_kelas'		=> 'required|exists:t_kelas',
			'foto'			=> 'required|mimes:jpeg,png|max:512'	
		];

		$this->validate($re,$rules);

		$input = $re->all();
		
		if($re->hasFile('foto') && $re->file('foto')->isValid()){
			$filename = $input['nis']. "." . $re->file('foto')->getClientOriginalExtension();
			$re->file('foto')->storeAs('',$filename);
			$input['foto'] = $filename;
		}

		$status = \App\Siswa::create($input);

		if($status) 
			return redirect('siswa/')->with('success','Data Berhasil Ditambahkan');
		else
			return redirect('siswa/')->with('error','Data Gagal Ditambahkan');
	}

	public function edit($id)
	{
		$data['result'] = \App\Siswa::where('nis',$id)->first();
		return view('siswa/form')->with($data);
	}

	public function update(Request $re,$id)
	{
		$rules = [
			'nama_lengkap'	=> 'required|max:100',
			'jenis_kelamin'	=> 'required',
			'alamat'		=> 'required',
			'no_hp'			=> 'required',
			'id_kelas'		=> 'required|exists:t_kelas',
			'foto'			=> 'mimes:jpeg,png|max:512'
		];

		$this->validate($re,$rules);
		$input = $re->all();

		if($re->hasFile('foto') && $re->file('foto')->isValid()){
			$filename = $input['nis']. "." . $re->file('foto')->getClientOriginalExtension();
			$re->file('foto')->storeAs('',$filename);
			$input['foto'] = $filename;
		}
		
		$result = \App\Siswa::where('nis',$id)->first();
		$status = $result->update($input);

		if($status) 
			return redirect('siswa/')->with('success','Data Berhasil Diubah');
		else
			return redirect('siswa/')->with('error','Data Gagal Diubah');

	}

	public function destroy(Request $re,$id)
	{
		$result = \App\Siswa::where('nis',$id)->first();
		$status = $result->delete();

		if($status) 
			return redirect('siswa/')->with('success','Data Berhasil Dihapus');
		else
			return redirect('siswa/')->with('error','Data Gagal Dihapus');
	}
}

app/Http/Controllers/kelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class kelasController extends Controller
{
	public function index()
	{
		$data['result'] = \App\Kelas::all();
		return view('kelas/index')->with($data);
	}

	public function create(){
		return view('kelas/form');
	}

	public function store(Request $r)
	{
		$rules = [
			'nama_kelas'	=> 'required|max:100',
			'jurusan'		=> 'required|max:100'
		];

		$this->validate($r,$rules);

		$input = $r->all();
		// $status = DB::table('t_kelas')->insertGetId([]);
		$status = \App\Kelas::create($input);
		if($status)
			return redirect('/')->with('success','Data Berhasil ditambahkan');
		else
			return redirect('/')->with('error','Data Gagal ditambahkan');
		
	}

	//edit

	public function edit($id){
		$data['result'] = \App\Kelas::where('id_kelas',$id)->first();
		return view('kelas/form')->with($data);
	}

	public function update(Request $re, $id)
	{
		$rules = [
			'nama_kelas'	=> 'required|max:100',
			'jurusan'		=> 'required|max:100'
		];

		$this->validate($re,$rules);

		$input = $re->all();
		$result = \App\Kelas::where('id_kelas',$id)->first();
		$status = $result->update($input);

		if($status)
			return redirect('/')->with('success','Data Berhasil diupdate');
		else
			return redirect('/')->with('error','Data Gagal diupdate');
	}

	public function destroy(Request $re,$id)
	{
		$result = \App\Kelas::where('id_kelas',$id)->first();
		$status = $result->delete($result);

		if($status)
			return redirect('/')->with('success','Data Berhasil dihapus');
		else
			return redirect('/')->with('error','Data Gagal dihapus');
	}
}

resources/views/kelas/form.blade.php
@extends('templates/header')

@section('content')
    <section class="content-header">
      <h1>
       {{ empty($result) ? 'Tambah' : 'Edit'}} Data Kelas
        <small>SMKN 4 BANDUNG</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Data Kelas</li>
        <li class="active">{{ empty($result) ? 'Tambah' : 'Edit' }} Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
@include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <a class="btn btn-purple" href="{{ url('/') }}"><i class="fa fa-arrow-left"></i> Kembali</a>
          </h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <form action="{{ empty($result) ? url('kelas/add') : url("kelas/$result->id_kelas/edit") }}"  method="POST" role="form">
            {{ csrf_field() }}

            @if (!empty($result))
              {{method_field('patch')}}
            @endif

            <div class="form-group">
              <label for="" class="control-label">Nama kelas</label>
              <input type="text" class="form-control" id="" placeholder="Nama Kelas" name="nama_kelas" value="{{@$result->nama_kelas}}">
            </div>

            <div class="form-group">
              <label for="" class="control-label">Jurusan</label>
              <input type="text" class="form-control" id="" placeholder="Jurusan" value="{{@$result->jurusan}}" name="jurusan">
            </div>         
            
          
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <!-- /.box-body -->
       <!--  <div class="box-footer">
          Footer
        </div> -->
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@endsection

resources/views/kelas/index.blade.php
@extends('templates/header')

@section('content')
    <section class="content-header">
      <h1>
        Data Kelas
        <small>SMKN 4 BANDUNG</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Smkn 4 Bandung</a></li>
        <li class="active">Data Kelas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <a class="btn btn-purple" href="{{ url('kelas/add') }}"> Tambah</a>
          </h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama Kelas</th>
                <th>Jurusan</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

            @foreach($result as $row)
              <tr>
                <td>{{ !empty($i) ? ++$i : $i = 1 }}</td>
                <td>{{ $row->nama_kelas }}</td>
                <td>{{ $row->jurusan }}</td>
                <td>
                  
                  <a href="{{ url("kelas/$row->id_kelas/edit") }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil">  </i></a>
<!-- 
                  <a href="{{ url("kelas/$row->id_kelas/delete") }}" class="btn btn-sm btn-danger"><i class="fa fa-trash">  </i></a> -->

                  <form action="{{ url("kelas/$row->id_kelas/delete") }}" method="POST" style="display:inline">
                    
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}

                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>

                  </form>

                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
       <!--  <div class="box-footer">
          Footer
        </div> -->
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>1516116255_XII-RPL3_IrvanLutfiGunawan</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ asset('assets') }}/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('assets') }}/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/iCheck/square/blue.css">

  <link rel="stylesheet" href="{{ asset('assets') }}/dist/css/custom.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page" style="background-image: url('{{asset('assets')}}/dist/img/pexels.jpeg')">

  <div class="login-box">
    <!-- /.login-logo -->
    <div class="login-box-body">
    <div class="login-logo">
      <a href="{{ url('login') }}"><b>Admin</b>LTE</a>
    </div>
      <p class="login-box-msg">Sign in to start your session</p>
      @include('templates.feedback')

      <form action="{{ url('login') }}" method="post">
        {{csrf_field()}}
        <div class="form-group has-feedback">
          <input type="text" class="form-control" placeholder="Username" name="username">
          <span class="fa fa-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="password" class="form-control" name="password" placeholder="Password">
          <span class="fa fa-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox" name="remember"> Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

    <!--   <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
          Facebook</a>
        <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
          Google+</a>
      </div> -->
      <!-- /.social-auth-links -->

      <a href="#">I forgot my password</a><br>
      <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
  </div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="{{ asset('assets') }}/plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ asset('assets') }}/bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="{{ asset('assets') }}/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>

resources/views/siswa/form.blade.php
@extends('templates/header')

@section('content')
    <section class="content-header">
      <h1>
       {{ empty($result) ? 'Tambah' : 'Edit'}} Data Siswa
        <small>SMKN 4 BANDUNG</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Data Siswa</li>
        <li class="active">{{ empty($result) ? 'Tambah' : 'Edit' }} Data Siswa</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
@include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <a class="btn btn-purple" href="{{ url('siswa/') }}"><i class="fa fa-arrow-left"></i> Kembali</a>
          </h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <form action="{{ empty($result) ? url('siswa/add') : url("siswa/$result->nis/edit") }}"  method="POST" role="form" enctype="multipart/form-data">
            {{ csrf_field() }}

            @if (!empty($result))
              {{method_field('patch')}}
            @endif

            <div class="form-group">
              <label for="" class="control-label">Nis</label>
              <input type="number" class="form-control" id="" placeholder="NIS" name="nis"  value="{{@$result->nis}}">
            </div>

            <div class="form-group">
              <label for="" class="control-label">Nama lengkap</label>
              <input type="text" class="form-control" id="" placeholder="Nama lengkap" value="{{@$result->nama_lengkap}}" name="nama_lengkap">
            </div>     

             <div class="form-group">
              <label for="" class="control-label">Jenis Kelamin</label>
              <div class="checkbox">
                <label><input type="radio" name="jenis_kelamin" value="L" {{(@$result->jenis_kelamin == 'L' ? 'checked' : '')}}>  Laki - Laki </label>
                <label><input type="radio" name="jenis_kelamin" value="P" {{(@$result->jenis_kelamin == 'P' ? 'checked' : '')}} > Perempuan </label>
              </div>

              <div class="form-group">
                <label for="" class="control-label">Alamat</label>
                <textarea type="text" class="form-control" id="" placeholder="Alamat" name="alamat">{!! @$result->alamat !!}</textarea>
              </div>   

               <div class="form-group">
                <label for="" class="control-label">No Telp</label>
                <input type="number" class="form-control" id="" placeholder="No Telp" value="{{@$result->no_hp}}" name="no_hp" maxlength="13" minlength="13">
              </div> 


               <div class="form-group">
                <label for="" class="control-label">Kelas</label>
                <select name="id_kelas" class="form-control">
                  @foreach (\App\Kelas::all() as $kelas)
                    <option value="{{$kelas->id_kelas}}" {{@$result->id_kelas == $kelas->id_kelas ? 'selected' : ''}}> {{@$kelas->nama_kelas}} </option>
                  @endforeach
                </select>
              </div>          
              <div class="form-group">
                <label for="" class="control-label">Foto</label>
                <input type="file" name="foto">
              </div>
            </div>       
            
          
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <!-- /.box-body -->
       <!--  <div class="box-footer">
          Footer
        </div> -->
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@endsection

resources/views/siswa/index.blade.php
@extends('templates/header')

@section('content')
    <section class="content-header">
      <h1>
        Data Siswa
        <small>SMKN 4 BANDUNG</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Smkn 4 Bandung</a></li>
        <li class="active">Data Siswa</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
    @include('templates/feedback')
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">
            <a class="btn btn-purple" href="{{ url('siswa/add') }}">Tambah</a>
          </h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>No</th>
                <th>Foto</th>
                <th>Nama Lengkap</th>
                <th>Jenis Kelamin</th>
                <th>Alamat</th>
                <th>No Telp</th>
                <th>Kelas</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            @foreach($result as $row)
              <tr>
                <td>{{ !empty($i) ? ++$i : $i = 1 }}</td>
                <td>
                  <img src="{{asset('uploads/'.@$row->foto)}}" class="img img-circle img-index" alt="">
                </td>
                <td>{{ @$row->nama_lengkap }}</td>
                <td>{{ @$row->jenis_kelamin_display }}</td>
                <td>{{ @$row->alamat }}</td>
                <td>{{ @$row->no_hp }}</td>
                <td>{{ @$row->kelas->nama_kelas }}</td>
                <td>
                  
                  <a href="{{ url("siswa/$row->nis/edit") }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil">  </i></a>
<!-- 
                  <a href="{{ url("kelas/$row->id_kelas/delete") }}" class="btn btn-sm btn-danger"><i class="fa fa-trash">  </i></a> -->

                  <form action="{{ url("siswa/$row->nis/delete") }}" method="POST" style="display:inline">
                    
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}

                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>

                  </form>

                </td>
              </tr>
            @endforeach
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
       <!--  <div class="box-footer">
          Footer
        </div> -->
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
@endsection

resources/views/templates/feedback.blade.php
@if(session('success'))
	<div class="alert alert-success fade in">
		<button class="close pull-right" type="button" data-dismiss="alert" arial-label="Close"> <span arial-hidden="true"></span> </button>
		{!! session('success') !!}
	</div>
@endif

@if(session('error'))
	<div class="alert alert-danger fade in">
		<button class="close pull-right" type="button" data-dismiss="alert" arial-label="Close"> <span arial-hidden="true"></span> </button>
		<p>Perhatian</p>

		{!! session('error') !!}
	</div>
@endif

@if(count($errors) > 0)
	<div class="alert alert-danger fade in">
		<button class="close pull-right" type="button" data-dismiss="alert" arial-label="Close"> <span arial-hidden="true"></span> </button>
		<p>Perhatian</p>
		<ul>
			@foreach($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif